Repository DFE-Digital/apply-for-qualified-teacher-status, pull requests merged in 2022-07, with the labels that each got.

#212 Add checkout step
  .github/workflows/delete-review-app.yml
Labels: deploy

#217 Fix typo on AZ command
  .github/workflows/delete-review-app.yml
Labels: deploy

#221 Fix typo on blob name
  .github/workflows/delete-review-app.yml
Labels: deploy

#222 Add placeholder docker image terraform var
  .github/workflows/delete-review-app.yml
Labels: deploy

#219 596 implement backups for apply for qts
  .github/workflows/database-backup.yml
  Makefile
  bin/download-db-backup
  bin/restore-db
Labels: devops

#232 integrated prometheus and grafana.
  terraform/app.tf
  terraform/data.tf
  terraform/network-policies.tf
  terraform/variables.tf
  terraform/workspace_variables/dev.tfvars.json
  terraform/workspace_variables/production.tfvars.json
Labels: devops

#239 Added statuscake alerts for apply for qts
  terraform/.terraform.lock.hcl
  terraform/provider.tf
  terraform/statuscake.tf
  terraform/terraform.tf
  terraform/variables.tf
  terraform/workspace_variables/dev.tfvars.json
  terraform/workspace_variables/preprod.tfvars.json
  terraform/workspace_variables/production.tfvars.json
  terraform/workspace_variables/test.tfvars.json
Labels: devops

#242 Add Logit service
  terraform/variables.tf
  terraform/workspace_variables/dev.tfvars.json
  terraform/workspace_variables/review.tfvars.json
Labels: devops, deploy
