Repository DFE-Digital/apply-for-qualified-teacher-status, pull requests merged in 2022-10, with the labels that each got.

#570 [992] Make application form requirements dynamic
  app/helpers/proof_of_recognition_helper.rb
  app/views/shared/_eligible_region_content.html.erb
  app/views/teacher_interface/uploads/new.html.erb
  spec/helpers/proof_of_recognition_helper_spec.rb
Labels: deploy

#582 Remove unneeded make variables
  Makefile
Labels: devops

#596 Work history updates
  app/forms/teacher_interface/work_history_form.rb
  app/models/work_history.rb
  app/views/shared/application_form/_work_history_summary.html.erb
  config/locales/teacher_interface.en.yml
  spec/forms/teacher_interface/work_history_form_spec.rb
  spec/models/work_history_spec.rb
Labels: deploy

#610 Added Check Service Principal workflow
  .github/workflows/check_sp.yml
Labels: devops

#639 Change set-output to GITHUB_OUTPUT
  .github/workflows/actions/deploy-environment/action.yml
  .github/workflows/deploy.yml
Labels: devops, deploy
