Repository DFE-Digital/apply-for-qualified-teacher-status, pull requests merged in 2022-08, with the labels that each got.

#283 Add smoke test
  .github/workflows/actions/smoke-test/action.yml
  .github/workflows/deploy.yml
Labels: devops, deploy

#304 Remove Deploy_dev job
  .github/workflows/deploy.yml
Labels: devops

#313 Move rspec test job to deploy
  .github/workflows/deploy.yml
  .github/workflows/test.yml
Labels: devops, deploy

#292 Added storage account for storing forms.
  .github/workflows/deploy.yml
  Makefile
  config/environments/production.rb
  config/storage.yml
  terraform/app.tf
  terraform/storage.tf
  terraform/variables.tf
  terraform/workspace_variables/dev.tfvars.json
  terraform/workspace_variables/preprod.tfvars.json
  terraform/workspace_variables/production.tfvars.json
  terraform/workspace_variables/test.tfvars.json
Labels: deploy

#340 Destroying review apps should destory storage as well.
  terraform/storage.tf
Labels: deploy

#358 Don't upload name change if not required
  app/controllers/teacher_interface/personal_information_controller.rb
  spec/system/teacher_interface/application_spec.rb
Labels: deploy

#357 Fix qualifications completed status
  app/models/application_form.rb
  app/models/qualification.rb
  spec/factories/qualifications.rb
  spec/models/qualification_spec.rb
Labels: deploy

#352 Move "Providing certified translations" in to an accordion
  app/views/shared/_eligible_region_content.html.erb
  spec/system/support_interface/countries_spec.rb
Labels: deploy

#354 Improve summary views
  app/views/teacher_interface/identity_document/_summary.html.erb
  app/views/teacher_interface/personal_information/_summary.html.erb
  app/views/teacher_interface/work_histories/_summary.html.erb
  app/views/teacher_interface/written_statement/_summary.html.erb
  spec/system/teacher_interface/application_spec.rb
Labels: deploy

#350 Only show "Check your answers" if section is complete
  app/controllers/teacher_interface/personal_information_controller.rb
  app/controllers/teacher_interface/qualifications_controller.rb
  app/controllers/teacher_interface/work_histories_controller.rb
  app/models/application_form.rb
  app/models/document.rb
  app/views/teacher_interface/personal_information/alternative_name.html.erb
  app/views/teacher_interface/personal_information/check.html.erb
  app/views/teacher_interface/personal_information/name_and_date_of_birth.html.erb
  app/views/teacher_interface/qualifications/check.html.erb
  app/views/teacher_interface/work_histories/check.html.erb
  app/views/teacher_interface/work_histories/new.html.erb
  config/routes.rb
  spec/models/document_spec.rb
  spec/system/teacher_interface/application_spec.rb
Labels: deploy

#367 Update seeds and run in review
  .github/workflows/actions/deploy-environment/action.yml
  .github/workflows/deploy.yml
  db/seeds.rb
Labels: deploy

#372 Set a content security policy
  config/initializers/content_security_policy.rb
Labels: deploy

#393 Add libvips-dev to runtime dependencies
  Dockerfile
  Gemfile
  lib/tasks/example_data.rake
Labels: deploy

#394 Improve how reference is generated
  app/models/application_form.rb
  spec/factories/application_forms.rb
  spec/models/application_form_spec.rb
Labels: deploy

#376 Use autocompleting country picker
  app/controllers/teacher_interface/qualifications_controller.rb
  app/controllers/teacher_interface/work_histories_controller.rb
  app/helpers/qualification_helper.rb
  app/helpers/work_history_helper.rb
  app/javascript/application.js
  app/models/country.rb
  app/models/eligibility_check.rb
  app/models/qualification.rb
  app/models/work_history.rb
  app/views/teacher_interface/qualifications/_form.html.erb
  app/views/teacher_interface/qualifications/_summary.html.erb
  app/views/teacher_interface/work_histories/_form.html.erb
  app/views/teacher_interface/work_histories/_summary.html.erb
  config/analytics.yml
  db/migrate/20220817125214_rename_country_to_country_code.rb
  db/schema.rb
  spec/factories/qualifications.rb
  spec/factories/work_histories.rb
  spec/helpers/qualification_helper_spec.rb
  spec/helpers/work_history_spec.rb
  spec/models/qualification_spec.rb
  spec/models/work_history_spec.rb
  spec/system/teacher_interface/application_spec.rb
Labels: deploy

#390 Add sign out link to navigation bar
  app/views/layouts/base.html.erb
  app/views/teacher_interface/application_forms/show.html.erb
  config/initializers/devise.rb
  spec/system/teacher_interface/authentication_spec.rb
Labels: deploy

#397 [778] Set correct `HostingEnvironment.host` for review
  app/lib/hosting_environment.rb
  spec/lib/hosting_environment_spec.rb
Labels: deploy

#402 [779] Configure review apps
  .github/workflows/deploy.yml
  lib/tasks/review_app.rake
Labels: deploy

#404 Persona logins
  .github/workflows/deploy.yml
  app/assets/stylesheets/application.sass.scss
  app/controllers/assessor_interface/application_forms_controller.rb
  app/controllers/personas_controller.rb
  app/controllers/staff/sessions_controller.rb
  app/helpers/personas_helper.rb
  app/models/application_form.rb
  app/models/feature_flag.rb
  app/models/qualification.rb
  app/models/work_history.rb
  app/views/assessor_interface/application_forms/index.html.erb
  app/views/layouts/base.html.erb
  app/views/personas/index.html.erb
  app/views/staff/sessions/new.html.erb
  config/routes.rb
  lib/tasks/example_data.rake
  lib/tasks/review_app.rake
  spec/factories/application_forms.rb
  spec/factories/staff.rb
  spec/factories/teachers.rb
  spec/models/work_history_spec.rb
  spec/system/assessor_spec.rb
  spec/system/personas_spec.rb
Labels: deploy
