Repository DFE-Digital/apply-for-qualified-teacher-status, pull requests merged in 2024-10, with the labels that each got.

#2421 Update GitHub Actions workflow to run RSpec system and other tests in…
  .github/workflows/deploy.yml
Labels: deploy

#2422 [AQTS-585][AQTS-591] Submission and LoPS request journeys (Nigeria, Hong Kong & Alberta, Canada)
  app/lib/country_name.rb
  app/mailers/teacher_mailer.rb
  app/models/professional_standing_request.rb
  app/services/submit_application_form.rb
  app/view_objects/teacher_interface/application_form_view_object.rb
  app/views/shared/eligible_region_content_components/_proof_of_recognition.html.erb
  app/views/teacher_interface/application_forms/show.html.erb
  app/views/teacher_interface/application_forms/show/_preliminary_check_pending.html.erb
  app/views/teacher_interface/application_forms/show/_request_professional_standing_certificate.html.erb
  app/views/teacher_interface/application_forms/show/_submitted.html.erb
  app/views/teacher_mailer/application_received.text.erb
  app/views/teacher_mailer/initial_checks_required.text.erb
  app/views/teacher_mailer/professional_standing_received.text.erb
  app/views/teacher_mailer/professional_standing_requested.text.erb
  config/locales/mailer.en.yml
  spec/lib/country_name_spec.rb
  spec/mailers/teacher_mailer_spec.rb
  spec/models/professional_standing_request_spec.rb
  spec/services/submit_application_form_spec.rb
  spec/system/assessor_interface/pre_assessment_tasks_spec.rb
  spec/system/teacher_interface/submitting_spec.rb
  spec/view_objects/teacher_interface/application_form_view_object_spec.rb
  spec/views/shared/eligible_region_content_spec.rb
  spec/views/teacher_interface/application_forms_show_spec.rb
Labels: deploy

#2430 [AQTS-600] Assessor interface age range validations
  app/controllers/assessor_interface/assessment_recommendation_award_controller.rb
  app/forms/concerns/assessor_interface/age_range_subjects_form.rb
  app/views/shared/_age_range_subjects_form_fields.html.erb
  config/locales/assessor_interface.en.yml
  config/locales/helpers.en.yml
  spec/forms/assessor_interface/check_age_range_subjects_form_spec.rb
  spec/forms/assessor_interface/confirm_age_range_subjects_form_spec.rb
  spec/support/shared_examples/age_range_subjects_form.rb
  spec/system/assessor_interface/completing_assessment_spec.rb
Labels: enhancement, deploy

#2442 [2041] Configure environment variables with yaml file
  docs/infrastructure.md
  terraform/application/.terraform.lock.hcl
  terraform/application/application.tf
  terraform/application/config/development/variables.tfvars.json
  terraform/application/config/development/variables.yml
  terraform/application/config/preproduction/variables.tfvars.json
  terraform/application/config/preproduction/variables.yml
  terraform/application/config/production/variables.tfvars.json
  terraform/application/config/production/variables.yml
  terraform/application/config/review/variables.tfvars.json
  terraform/application/config/review/variables.yml
  terraform/application/storage.tf
  terraform/application/variables.tf
Labels: devops, deploy

#2448 AQTS-622-Email-content-changes
  app/views/teacher_mailer/consent_submitted.text.erb
  app/views/teacher_mailer/further_information_received.text.erb
  config/locales/mailer.en.yml
  spec/mailers/teacher_mailer_spec.rb
Labels: deploy

#2450 Add missing test variables.yml file
  terraform/application/config/test/variables.tfvars.json
  terraform/application/config/test/variables.yml
Labels: devops

#2444 [AQTS-625] Validation for referee email address in CMS, FI & draft application when you save and continue
  app/forms/assessor_interface/work_history_contact_form.rb
  app/models/further_information_request_item.rb
  app/models/work_history.rb
  app/views/teacher_interface/further_information_request_items/edit.html.erb
  config/locales/teacher_interface.en.yml
  spec/models/further_information_request_item_spec.rb
  spec/models/work_history_spec.rb
Labels: bug, deploy

#2453 Afqts makefile correction
  Makefile
  global_config/development.sh
  global_config/domains.sh
  global_config/preprod.sh
  global_config/production.sh
  global_config/review.sh
  global_config/test.sh
  terraform/application/.terraform.lock.hcl
Labels: deploy

#2434 AQTS-613 Support console validation for teaching authority email
  app/forms/support_interface/region_form.rb
  spec/forms/support_interface/region_form_spec.rb
Labels: deploy

#2439 [AQTS-562] Updates flows as per design for gov one registration sign in and signing out
  app/controllers/teachers/registrations_controller.rb
  app/controllers/teachers/sessions_controller.rb
  app/forms/teacher_interface/new_session_form.rb
  app/views/eligibility_interface/result/eligible.html.erb
  app/views/eligibility_interface/start/show.erb
  app/views/shared/_header.html.erb
  app/views/teacher_interface/application_forms/show/_draft.html.erb
  app/views/teacher_interface/consent_requests/index.html.erb
  app/views/teacher_interface/further_information_requests/show.html.erb
  app/views/teacher_mailer/application_not_submitted.text.erb
  app/views/teacher_mailer/consent_reminder.text.erb
  app/views/teacher_mailer/consent_requested.text.erb
  app/views/teacher_mailer/further_information_reminder.text.erb
  app/views/teacher_mailer/further_information_requested.text.erb
  app/views/teachers/registrations/new.html.erb
  app/views/teachers/sessions/new.html.erb
  app/views/teachers/sessions/new_or_create.html.erb
  spec/mailers/teacher_mailer_spec.rb
  spec/requests/teachers/registrations/create_spec.rb
  spec/requests/teachers/registrations/new_spec.rb
  spec/requests/teachers/sessions/create_spec.rb
  spec/requests/teachers/sessions/new_spec.rb
  spec/views/eligibility_interface/result/eligible_spec.rb
  spec/views/eligibility_interface/start/show_spec.rb
  spec/views/teacher_interface/application_forms/show_spec.rb
Labels: deploy

#2464 [AQTS-641] Remove OLI content from start page
  app/views/eligibility_interface/start/show.erb
  spec/views/eligibility_interface/start/show_spec.rb
Labels: deploy

#2456 [AQTS-633] If user has no account and attempts to sign in they should go through eligibility check
  app/controllers/teachers/omniauth_callbacks_controller.rb
  app/models/eligibility_check.rb
  app/services/find_or_create_teacher_from_gov_one.rb
  spec/models/eligibility_check_spec.rb
  spec/rails_helper.rb
  spec/requests/teachers/omniauth_callbacks/gov_one_spec.rb
  spec/services/find_or_create_teacher_from_gov_one_spec.rb
  spec/support/set_session_helpers.rb
Labels: deploy

#2461 Updated content for sign out page
  app/views/teachers/sessions/signed_out.html.erb
  spec/system/teacher_interface/consent_spec.rb
Labels: deploy
