Repository DFE-Digital/apply-for-qualified-teacher-status, pull requests merged in 2024-09, with the labels that each got.

#2379 Add teacher license form for Ghana
  Gemfile.lock
  app/controllers/teacher_interface/registration_number_controller.rb
  app/forms/teacher_interface/ghana_registration_number_form.rb
  app/lib/application_form_section_status_updater.rb
  app/lib/country_code.rb
  app/lib/registration_number_validators/ghana.rb
  app/view_objects/teacher_interface/application_form_view_object.rb
  app/views/shared/application_form/_registration_number_summary.html.erb
  app/views/teacher_interface/registration_number/edit.html.erb
  app/views/teacher_interface/registration_number/edit_ghana.html.erb
  config/locales/helpers.en.yml
  config/locales/teacher_interface.en.yml
  spec/forms/teacher_interface/ghana_registration_number_form_spec.rb
  spec/lib/application_form_section_status_updater_spec.rb
  spec/lib/registration_number_validators/ghana_spec.rb
  spec/support/autoload/page_objects/teacher_interface/application.rb
  spec/support/autoload/page_objects/teacher_interface/ghana_registration_number.rb
  spec/support/page_helpers.rb
  spec/system/teacher_interface/registration_numbers/ghana_registration_number_spec.rb
Labels: deploy

#2372 Content changes for communication in submission timeline
  app/view_objects/teacher_interface/application_form_view_object.rb
  app/views/teacher_interface/application_forms/show/_submitted.html.erb
  app/views/teacher_mailer/application_received.text.erb
  spec/mailers/teacher_mailer_spec.rb
  spec/system/teacher_interface/submitting_spec.rb
  spec/views/teacher_interface/application_forms_show_spec.rb
Labels: deploy

#2395 AQTS-410 DEV Eligibility criteria has changed banner is showing on applications where the prelim check has changed since submission
  app/models/application_form.rb
  spec/models/application_form_spec.rb
Labels: deploy

#2392 [AQTS-550] Ensure if check and select consent method is not complete, other task items do not appear
  app/view_objects/assessor_interface/qualification_requests_view_object.rb
  spec/view_objects/assessor_interface/qualification_requests_view_object_spec.rb
Labels: bug, deploy

#2404 AQTS-571 Incorrect title for FI from applicant in assessor interface
  config/locales/assessor_interface.en.yml
  spec/support/autoload/page_objects/assessor_interface/application.rb
  spec/view_objects/assessor_interface/application_forms_show_view_object_spec.rb
Labels: deploy

#2410 AQTS-581 Revert the content for countries where teaching authority provides written statement
  app/views/teacher_interface/application_forms/show/_submitted.html.erb
Labels: deploy

#2416 Updated pipeline to use shared action
  .github/workflows/database.yaml
Labels: devops

#2401 [AQTS-551] GovOne Login Authentication
  Gemfile
  Gemfile.lock
  adr/00010-govuk-one-login.md
  app/controllers/teachers/omniauth_callbacks_controller.rb
  app/helpers/gov_one_helper.rb
  app/models/teacher.rb
  app/services/find_or_create_teacher_from_gov_one.rb
  app/views/shared/_header.html.erb
  app/views/teachers/registrations/new.html.erb
  app/views/teachers/sessions/new.html.erb
  config/analytics_blocklist.yml
  config/application.rb
  config/feature_flags.yml
  config/gov_one.yml
  config/initializers/omniauth.rb
  config/routes.rb
  db/migrate/20240910153044_add_gov_one_id_to_teacher_record.rb
  db/schema.rb
  docs/diagram.pdf
  spec/factories/teachers.rb
  spec/models/teacher_spec.rb
  spec/rails_helper.rb
  spec/requests/teachers/omniauth_callbacks/gov_one_spec.rb
  spec/services/find_or_create_teacher_from_gov_one_spec.rb
  spec/system/support_interface/staff_spec.rb
Labels: enhancement, deploy

#2409 [AQTS-578] Ability to archive staff in support console
  app/controllers/support_interface/staff_controller.rb
  app/models/staff.rb
  app/policies/assessor_interface/application_form_policy.rb
  app/policies/assessor_interface/assessment_policy.rb
  app/policies/assessor_interface/assessment_recommendation_policy.rb
  app/policies/assessor_interface/assessment_section_policy.rb
  app/policies/assessor_interface/consent_request_policy.rb
  app/policies/assessor_interface/further_information_request_policy.rb
  app/policies/assessor_interface/note_policy.rb
  app/policies/assessor_interface/professional_standing_request_policy.rb
  app/policies/assessor_interface/qualification_request_policy.rb
  app/policies/assessor_interface/reference_request_policy.rb
  app/policies/assessor_interface/staff_assignment_policy.rb
  app/policies/assessor_interface/suitability_record_policy.rb
  app/policies/assessor_interface/work_history_policy.rb
  app/policies/support_interface/country_policy.rb
  app/policies/support_interface/english_language_provider_policy.rb
  app/policies/support_interface/feature_flag_policy.rb
  app/policies/support_interface/region_policy.rb
  app/policies/support_interface/staff_policy.rb
  config/analytics.yml
  config/routes.rb
  db/migrate/20240919143157_add_archived_to_staff.rb
  db/schema.rb
  docs/diagram.pdf
  spec/factories/staff.rb
  spec/models/staff_spec.rb
  spec/support/shared_examples/policy.rb
  spec/support/system_helpers.rb
  spec/system/assessor_interface/assigning_assessor_spec.rb
  spec/system/assessor_interface/authentication_spec.rb
  spec/system/assessor_interface/change_application_form_email_spec.rb
  spec/system/assessor_interface/change_application_form_name_spec.rb
  spec/system/assessor_interface/change_work_history_spec.rb
  spec/system/assessor_interface/checking_submitted_details_spec.rb
  spec/system/assessor_interface/completing_assessment_spec.rb
  spec/system/assessor_interface/confirming_english_language_exemption_spec.rb
  spec/system/assessor_interface/creating_note_spec.rb
  spec/system/assessor_interface/requesting_further_information_spec.rb
  spec/system/assessor_interface/reviewing_further_information_spec.rb
  spec/system/assessor_interface/reviewing_professional_standing_spec.rb
  spec/system/assessor_interface/suitability_spec.rb
  spec/system/assessor_interface/verifying_professional_standing_spec.rb
  spec/system/assessor_interface/verifying_qualifications_spec.rb
  spec/system/assessor_interface/verifying_references_spec.rb
  spec/system/assessor_interface/view_application_form_spec.rb
  spec/system/assessor_interface/view_timeline_events_spec.rb
  spec/system/assessor_interface/withdraw_application_spec.rb
  spec/system/support_interface/countries_spec.rb
  spec/system/support_interface/english_language_providers_spec.rb
  spec/system/support_interface/features_spec.rb
  spec/system/support_interface/sidekiq_spec.rb
  spec/system/support_interface/staff_spec.rb
Labels: enhancement, deploy
