Repository DFE-Digital/apply-for-qualified-teacher-status, pull requests merged in 2025-03, with the labels that each got.

#2668 [AQTS-852] FI Content Changes
  config/locales/assessor_interface.en.yml
  config/locales/teacher_interface.en.yml
  spec/view_objects/teacher_interface/application_form_view_object_spec.rb
Labels: enhancement, deploy

#2667 [AQTS-796] Remove teaching confirmation being set to true on edit by default
  app/controllers/teacher_interface/qualifications_controller.rb
  spec/system/teacher_interface/back_links_spec.rb
  spec/system/teacher_interface/check_answers_spec.rb
Labels: bug, deploy

#2661 AQTS 834 add manage access link to assessor interface
  app/controllers/assessor_interface/staff_controller.rb
  app/controllers/staff/invitations_controller.rb
  app/policies/assessor_interface/staff_policy.rb
  app/views/assessor_interface/staff/_permissions_fields.html.erb
  app/views/assessor_interface/staff/edit.html.erb
  app/views/assessor_interface/staff/index.html.erb
  app/views/shared/_header.html.erb
  app/views/staff/invitations/new.html.erb
  config/routes.rb
  db/schema.rb
  spec/policies/assessor_interface/staff_policy_spec.rb
  spec/support/autoload/page_objects/assessor_interface/staff_index.rb
  spec/support/autoload/page_objects/page_header.rb
  spec/support/page_helpers.rb
  spec/system/assessor_interface/authentication_spec.rb
  spec/system/assessor_interface/staff_spec.rb
Labels: deploy

#2669 [AQTS-853] Work history FI updates
  app/forms/assessor_interface/assessment_section_form.rb
  app/lib/failure_reasons.rb
  app/view_objects/assessor_interface/assessment_section_view_object.rb
  app/views/assessor_interface/assessment_sections/_form.html.erb
  app/views/assessor_interface/further_information_requests/new.html.erb
  config/locales/assessor_interface.en.yml
  config/locales/helpers.en.yml
  config/locales/teacher_interface.en.yml
  spec/forms/assessor_interface/assessment_section_form_spec.rb
  spec/system/assessor_interface/checking_submitted_details_spec.rb
  spec/view_objects/assessor_interface/assessment_section_view_object_spec.rb
Labels: enhancement, deploy

#2676 [AQTS-854] Introducing new FI reasons
  app/jobs/sync_assessment_checks_and_failure_reasons_job.rb
  app/lib/assessment_factories/age_range_subjects_section.rb
  app/lib/assessment_factories/english_language_proficiency_section.rb
  app/lib/assessment_factories/personal_information_section.rb
  app/lib/assessment_factories/professional_standing_section.rb
  app/lib/assessment_factories/qualification_section.rb
  app/lib/assessment_factories/work_history_section.rb
  app/lib/assessment_factory.rb
  app/lib/failure_reasons.rb
  config/locales/assessor_interface.en.yml
  config/locales/teacher_interface.en.yml
  docs/assessment-checks-and-failure-reason-updates.md
  lib/tasks/assessment_sections.rake
  spec/jobs/sync_assessment_checks_and_failure_reasons_job_spec.rb
  spec/lib/assessment_factory_spec.rb
Labels: enhancement, deploy

#2677 AQTS 837 manage staff users permissions
  app/controllers/assessor_interface/staff_controller.rb
  app/controllers/personas_controller.rb
  app/controllers/staff/invitations_controller.rb
  app/lib/fake_data/staff_generator.rb
  app/models/staff.rb
  app/policies/assessor_interface/staff_policy.rb
  app/views/assessor_interface/staff/_permissions_fields.html.erb
  app/views/assessor_interface/staff/index.html.erb
  app/views/personas/_staff.html.erb
  app/views/shared/_header.html.erb
  config/analytics.yml
  config/locales/en.yml
  db/migrate/20250307150915_add_manage_staff_permission_to_staff.rb
  db/schema.rb
  docs/diagram.pdf
  spec/factories/staff.rb
  spec/models/staff_spec.rb
  spec/policies/assessor_interface/staff_policy_spec.rb
  spec/support/shared_examples/policy.rb
  spec/support/system_helpers.rb
  spec/system/assessor_interface/authentication_spec.rb
  spec/system/assessor_interface/staff_spec.rb
Labels: deploy

#2693 Update ruby back to 3.3.0
  .ruby-version
  .tool-versions
  Dockerfile
  Gemfile
  Gemfile.lock
  db/schema.rb
  docs/diagram.pdf
Labels: deploy

#2692 [AQTS-862] Remove review previous referee details on FI after it has been accepted
  app/views/assessor_interface/further_information_requests/edit.html.erb
  spec/system/assessor_interface/reviewing_further_information_spec.rb
Labels: deploy

#2696 [AQTS-863] Ensuring there is a link to sign in as applicant on test and review environments
  app/views/assessor_interface/application_forms/show.html.erb
Labels: deploy

#2695 AQTS-838-update-staff-frontend-design
  app/controllers/assessor_interface/staff_controller.rb
  app/models/staff.rb
  app/views/assessor_interface/staff/_active_users.html.erb
  app/views/assessor_interface/staff/_archived_users.html.erb
  app/views/assessor_interface/staff/index.html.erb
  spec/system/assessor_interface/staff_spec.rb
Labels: deploy

#2700 Move workflow secrets to github
  .github/workflows/deploy.yml
Labels: devops, deploy

#2699 [AQTS-900] Tracking of validation error triggering
  app/controllers/concerns/handle_application_form_section.rb
  app/controllers/teacher_interface/application_forms_controller.rb
  app/controllers/teacher_interface/qualifications_controller.rb
  app/controllers/teacher_interface/uploads_controller.rb
  app/controllers/teacher_interface/work_histories_controller.rb
  config/analytics_custom_events.yml
  spec/controllers/concerns/handle_application_form_section_spec.rb
  spec/rails_helper.rb
Labels: deploy
