Repository DFE-Digital/apply-for-qualified-teacher-status, pull requests merged in 2025-02, with the labels that each got.

#2625 [AQTS-812] Fix typo on English language certificate content
  app/views/shared/_english_language_approved_providers.html.erb
  app/views/shared/eligible_region_content_components/_english_language.html.erb
  app/views/teacher_interface/work_histories/add_another.html.erb
  app/views/teacher_interface/work_histories/requirements_unmet.html.erb
Labels: bug, deploy

#2606 [AQTS-760] Passport changes for assessment pages (Personal information section)
  app/lib/assessment_factory.rb
  app/lib/failure_reasons.rb
  app/view_objects/assessor_interface/assessment_section_view_object.rb
  app/view_objects/assessor_interface/further_information_request_view_object.rb
  app/view_objects/teacher_interface/further_information_request_view_object.rb
  app/views/assessor_interface/assessment_sections/_form.html.erb
  app/views/assessor_interface/assessment_sections/_personal_information_summary.html.erb
  config/locales/assessor_interface.en.yml
  config/locales/helpers.en.yml
  config/locales/teacher_interface.en.yml
  spec/factories/further_information_request_items.rb
  spec/lib/assessment_factory_spec.rb
  spec/view_objects/assessor_interface/assessment_section_view_object_spec.rb
  spec/view_objects/assessor_interface/further_information_request_view_object_spec.rb
  spec/view_objects/teacher_interface/further_information_request_view_object_spec.rb
Labels: deploy

#2632 [AQTS-759] Updating or Submitting a draft application when passport has expired
  app/controllers/teacher_interface/application_forms_controller.rb
  app/view_objects/teacher_interface/application_form_view_object.rb
  app/views/teacher_interface/application_forms/show/_draft.html.erb
  spec/support/autoload/page_objects/teacher_interface/application.rb
  spec/system/teacher_interface/submitting_spec.rb
Labels: deploy

#2630 [AQTS-761][AQTS-816] Copy changes to personal information section
  app/controllers/teacher_interface/personal_information_controller.rb
  app/forms/teacher_interface/alternative_name_form.rb
  app/forms/teacher_interface/name_and_date_of_birth_form.rb
  app/view_objects/teacher_interface/personal_information_view_object.rb
  app/views/shared/application_form/_personal_information_summary.html.erb
  app/views/teacher_interface/personal_information/alternative_name.html.erb
  app/views/teacher_interface/personal_information/name_and_date_of_birth.html.erb
  config/locales/helpers.en.yml
  config/locales/teacher_interface.en.yml
  spec/forms/teacher_interface/name_and_date_of_birth_form_spec.rb
  spec/system/teacher_interface/personal_information_spec.rb
  spec/view_objects/teacher_interface/personal_information_view_object_spec.rb
Labels: enhancement, deploy

#2634 [AQTS-818] Introduce "Your English language proficiency" section on "Check your answers" page for applicants
  app/views/teacher_interface/application_forms/edit.html.erb
  spec/support/autoload/page_objects/teacher_interface/check_your_answers.rb
  spec/system/teacher_interface/check_answers_spec.rb
Labels: bug, deploy

#2613 AQTS 782 remove archived staff
  app/view_objects/assessor_interface/application_forms_index_view_object.rb
  app/views/assessor_interface/assessor_assignments/new.html.erb
  app/views/assessor_interface/reviewer_assignments/new.html.erb
  spec/factories/staff.rb
  spec/rails_helper.rb
  spec/requests/assessor/applications/assign-assessor/new_spec.rb
  spec/requests/assessor/applications/assign-reviewer/new_spec.rb
  spec/view_objects/assessor_interface/application_forms_index_view_object_spec.rb
Labels: deploy

#2638 [AQTS-821] Introduce a view only page for applications that have been submitted
  app/controllers/teacher_interface/application_forms_controller.rb
  app/controllers/teacher_interface/uploads_controller.rb
  app/views/assessor_interface/assessment_sections/_work_history_summary.html.erb
  app/views/shared/application_form/_work_history_summary.html.erb
  app/views/teacher_interface/application_forms/answers.html.erb
  app/views/teacher_interface/application_forms/edit.html.erb
  app/views/teacher_interface/work_histories/check_collection.html.erb
  app/views/teacher_interface/work_histories/check_member.html.erb
  config/routes.rb
  spec/controllers/teacher_interface/uploads_controller_spec.rb
  spec/support/autoload/page_objects/teacher_interface/view_your_answers.rb
  spec/support/page_helpers.rb
  spec/system/teacher_interface/view_answers_spec.rb
Labels: enhancement, deploy

#2645 [AQTS-832] Updating content related to level 6 teacher training qualification
  app/views/eligibility_interface/start/show.erb
  config/locales/helpers.en.yml
Labels: enhancement, deploy

#2647 [AQTS-833] Updating content for assessment of level 6 teaching qualifications
  app/lib/assessment_factory.rb
  config/locales/assessor_interface.en.yml
  config/locales/teacher_interface.en.yml
  spec/lib/assessment_factory_spec.rb
Labels: enhancement, deploy

#2657 [AQTS-799] Ensure logs exclude all parameters from forms on top of PI data
  config/initializers/filter_logging.rb
Labels: enhancement, deploy

#2652 [AQTS-817] Remove the need for taking the applicant to a specific step on english language proficiency
  app/controllers/teacher_interface/english_language_controller.rb
  spec/requests/teachers/english_language/show_spec.rb
Labels: bug, deploy

#2643 AQTS 781 show work history
  app/helpers/work_history_helper.rb
  app/views/shared/application_form/_work_history_summary.html.erb
  spec/helpers/work_history_helper_spec.rb
Labels: deploy

#2656 [AQTS-820] Fix missing captions not visible on some of the application tasks
  app/controllers/teacher_interface/documents_controller.rb
  app/controllers/teacher_interface/uploads_controller.rb
  app/view_objects/teacher_interface/document_view_object.rb
  app/views/teacher_interface/documents/edit_uploads.html.erb
  app/views/teacher_interface/registration_number/edit.html.erb
  app/views/teacher_interface/registration_number/edit_ghana.html.erb
  app/views/teacher_interface/uploads/new.html.erb
  app/views/teacher_interface/work_histories/_school_form.html.erb
  app/views/teacher_interface/work_histories/add_another.html.erb
  app/views/teacher_interface/work_histories/edit_contact.html.erb
  spec/view_objects/teacher_interface/document_view_object_spec.rb
Labels: deploy

#2644 [AQTS-822] Capture country of issue for passports
  app/controllers/autocomplete_passport_country_of_issues_controller.rb
  app/controllers/teacher_interface/passport_document_controller.rb
  app/forms/teacher_interface/passport_expiry_date_form.rb
  app/javascript/application.js
  app/lib/application_form_section_status_updater.rb
  app/lib/country_of_issue_for_passport.rb
  app/models/application_form.rb
  app/views/shared/application_form/_passport_document_summary.html.erb
  app/views/teacher_interface/passport_document/expired.html.erb
  app/views/teacher_interface/passport_document/expiry_date.html.erb
  config/analytics.yml
  config/analytics_hidden_pii.yml
  config/locales/teacher_interface.en.yml
  config/routes.rb
  db/migrate/20250212143034_add_passport_country_of_issue_to_application_form.rb
  db/schema.rb
  db/scripts/sanitise.sql
  docs/diagram.pdf
  public/passport-country-of-issue-autocomplete-graph.json
  public/passport-country-of-issue-canonical-list.json
  spec/factories/application_forms.rb
  spec/forms/teacher_interface/passport_expiry_date_form_spec.rb
  spec/lib/application_form_section_status_updater_spec.rb
  spec/lib/country_of_issue_for_passport_spec.rb
  spec/models/application_form_spec.rb
  spec/support/autoload/page_objects/teacher_interface/passport_expiry_date.rb
  spec/system/teacher_interface/passport_document_spec.rb
Labels: enhancement, deploy
