Repository DFE-Digital/apply-for-qualified-teacher-status, pull requests merged in 2025-01, with the labels that each got.

#2572 AQTS 754 update feedback form
  config/locales/en.yml
Labels: deploy

#2568 [AQTS-699] Removing `expire_after` from our session store
  config/initializers/session_store.rb
Labels: enhancement, deploy

#2597 Update nginx base image
  maintenance_page/Dockerfile
Labels: devops

#2602 All workflows using ubuntu-latest was impacted due to default Github actions runner has been updated from ubuntu-22.04 to ubuntu-24.04
  .github/workflows/codeql-analysis.yml
  .github/workflows/configuration-sync.yaml
  .github/workflows/database-ptr.yml
  .github/workflows/database-restore.yml
  .github/workflows/database.yaml
  .github/workflows/delete-review-app.yml
  .github/workflows/deploy.yml
  .github/workflows/fake-data.yaml
  .github/workflows/lint.yml
  .github/workflows/maintenance.yml
Labels: bug

#2587 [AQTS-758] Passport as ID for applicants
  adr/00007-application-forms.md
  app/controllers/teacher_interface/passport_document_controller.rb
  app/forms/teacher_interface/passport_expiry_date_form.rb
  app/lib/application_form_factory.rb
  app/lib/application_form_section_status_updater.rb
  app/lib/document_continue_redirection.rb
  app/models/application_form.rb
  app/models/document.rb
  app/view_objects/teacher_interface/application_form_view_object.rb
  app/views/shared/application_form/_passport_document_summary.html.erb
  app/views/teacher_interface/application_forms/edit.html.erb
  app/views/teacher_interface/passport_document/check.html.erb
  app/views/teacher_interface/passport_document/expiry_date.html.erb
  app/views/teacher_interface/uploads/new.html.erb
  config/analytics.yml
  config/feature_flags.yml
  config/locales/en.yml
  config/locales/helpers.en.yml
  config/locales/teacher_interface.en.yml
  config/routes.rb
  db/migrate/20250106152916_add_passport_document_fields_to_application_form.rb
  db/schema.rb
  docs/diagram.pdf
  lib/tasks/review_app.rake
  spec/factories/application_forms.rb
  spec/forms/teacher_interface/passport_expiry_date_form_spec.rb
  spec/lib/application_form_factory_spec.rb
  spec/lib/application_form_section_status_updater_spec.rb
  spec/lib/document_continue_redirection_spec.rb
  spec/models/application_form_spec.rb
  spec/models/document_spec.rb
  spec/services/destroy_application_form_spec.rb
  spec/support/autoload/page_objects/teacher_interface/application.rb
  spec/support/autoload/page_objects/teacher_interface/check_passport_document.rb
  spec/support/autoload/page_objects/teacher_interface/passport_expiry_date.rb
  spec/support/page_helpers.rb
  spec/system/teacher_interface/passport_document_spec.rb
  spec/system/teacher_interface/submitting_spec.rb
  spec/view_objects/teacher_interface/application_form_view_object_spec.rb
Labels: enhancement, deploy

#2601 AQTS-783 update status
  app/components/status_tag/component.rb
  spec/components/status_tag_spec.rb
Labels: deploy

#2607 [AQTS-795] Update the approved providers link for english language certificate
  app/views/assessor_interface/assessment_sections/_english_language_provider_details.html.erb
  app/views/shared/_english_language_approved_providers.html.erb
  app/views/shared/eligible_region_content_components/_english_language.html.erb
Labels: bug, deploy

#2616 Revert "[AQTS-795] Update the approved providers link for english language certificate"
  app/views/assessor_interface/assessment_sections/_english_language_provider_details.html.erb
  app/views/shared/_english_language_approved_providers.html.erb
  app/views/shared/eligible_region_content_components/_english_language.html.erb
Labels: bug

#2614 Update workflows to use ga wif
  .github/actions/deploy-environment/action.yml
  .github/actions/set-kubernetes-credentials/action.yaml
  .github/workflows/configuration-sync.yaml
  .github/workflows/database-ptr.yml
  .github/workflows/database-restore.yml
  .github/workflows/database.yaml
  .github/workflows/delete-review-app.yml
  .github/workflows/deploy.yml
  .github/workflows/fake-data.yaml
  .github/workflows/maintenance.yml
  Makefile
  terraform/application/providers.tf
Labels: devops, deploy

#2624 Adding postgres service to the sync preprod job
  .github/workflows/sync-preprod-with-sanitised-prod-backup.yaml
Labels: bug, devops

#2619 CI-CD for domains
  .github/workflows/deploy.yml
  Makefile
  global_config/domains.sh
  terraform/domains/environment_domains/output.tf
Labels: devops

#2628 Fixes to the sanitise sql which were broken
  db/scripts/sanitise.sql
Labels: bug

#2617 [AQTS-757] Content updates regarding passport proof on eligibility criteria
  app/views/eligibility_interface/start/show.erb
  app/views/shared/eligible_region_content_components/_english_language.html.erb
  app/views/shared/eligible_region_content_components/_proof_of_identity.html.erb
Labels: deploy
