Repository DFE-Digital/apply-for-qualified-teacher-status, pull requests merged in 2025-08, with the labels that each got.

#2825 [AQTS-1093] Prioritisation: invalidating the prioritisation referee link - rejected post overdue status
  app/models/prioritisation_reference_request.rb
  spec/system/teacher_interface/prioritisation_reference_spec.rb
Labels: deploy

#2827 Prioritisation content updates
  app/components/status_tag/component.rb
  app/views/assessor_interface/prioritisation_work_history_checks/edit.html.erb
  app/views/eligibility_interface/work_experience_in_england/new.html.erb
  app/views/teacher_interface/other_england_work_histories/_school_form.html.erb
  app/views/teacher_interface/other_england_work_histories/add_another.html.erb
  app/views/teacher_interface/other_england_work_histories/edit_contact.html.erb
  app/views/teacher_interface/other_england_work_histories/edit_meets_criteria.html.erb
  app/views/teacher_mailer/application_not_prioritised.text.erb
  app/views/teacher_mailer/application_received.text.erb
  config/locales/components.en.yml
  spec/view_objects/assessor_interface/application_forms_index_view_object_spec.rb
Labels: deploy

#2833 [AQTS-1023] Update prioritisation guidance document link
  app/views/assessor_interface/prioritisation_work_history_checks/edit.html.erb
  app/views/eligibility_interface/result/ineligible.html.erb
  app/views/eligibility_interface/start/show.erb
  app/views/shared/_assessment_process_timeline.html.erb
  app/views/shared/eligible_region_content_components/_proof_of_work_history.html.erb
  app/views/teacher_interface/application_forms/show/_submitted.html.erb
  app/views/teacher_mailer/application_received.text.erb
  app/views/teacher_mailer/professional_standing_received.text.erb
Labels: deploy

#2830 [AQTS-1125] Ensure uploaded translated documents are displayed for FI responses
  app/views/assessor_interface/further_information_requests/edit.html.erb
Labels: bug, deploy

#2829 Use non-root user
  Dockerfile
  terraform/application/application.tf
  terraform/application/variables.tf
Labels: devops, deploy

#2835 AQTS 1042 FI request start page
  app/views/teacher_interface/application_forms/show/_further_information_requested.html.erb
  spec/system/teacher_interface/further_information_spec.rb
Labels: deploy

#2842 [AQTS-1130] Link Eligibility checker with application forms
  app/controllers/teachers/registrations_controller.rb
  app/lib/application_form_factory.rb
  app/models/application_form.rb
  app/services/find_or_create_teacher_from_gov_one.rb
  config/analytics.yml
  db/migrate/20250812142312_add_eligibility_check_reference_to_application_forms.rb
  db/schema.rb
  docs/diagram.pdf
  spec/factories/application_forms.rb
  spec/lib/application_form_factory_spec.rb
  spec/models/application_form_spec.rb
  spec/services/find_or_create_teacher_from_gov_one_spec.rb
Labels: deploy

#2849 AQTS 1138 reorder cms applications
  app/view_objects/assessor_interface/application_forms_index_view_object.rb
  spec/system/assessor_interface/listing_application_forms_spec.rb
  spec/view_objects/assessor_interface/application_forms_index_view_object_spec.rb
Labels: deploy

#2841 [AQTS-1049] Changes to English language providers
  app/controllers/support_interface/english_language_providers_controller.rb
  app/models/english_language_provider.rb
  app/views/assessor_interface/assessment_sections/_english_language_provider_details.html.erb
  app/views/static/english_language_guidance.html.erb
  app/views/support_interface/english_language_providers/edit.html.erb
  app/views/support_interface/english_language_providers/index.html.erb
  app/views/teacher_interface/english_language/edit_provider_reference.html.erb
  config/analytics.yml
  config/locales/helpers.en.yml
  db/migrate/20250811145745_add_other_information_to_english_language_providers.rb
  db/schema.rb
  docs/diagram.pdf
  spec/factories/english_language_providers.rb
  spec/models/english_language_provider_spec.rb
Labels: deploy

#2839 AQTS 1041 update fi emails
  app/views/shared/teacher_mailer/_any_questions_contact.text.erb
  app/views/teacher_mailer/further_information_reminder.text.erb
  app/views/teacher_mailer/further_information_requested.text.erb
  spec/mailers/teacher_mailer_spec.rb
Labels: deploy

#2860 Add recover db workflow
  .github/workflows/postgres-recover-deleted-db.yml
Labels: devops, deploy
